### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by VirtualPandaVR**
Adding Panda's Immersive SkyrimVR Experience

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
your last PR was actually correct but the file you are linking to had some problems that were causing the test to fail. but in this PR your edit to the json is breaking the json.

**Comment by VirtualPandaVR** [comment]
@EzioTheDeadPoet probably because someone forgot to put a comma on the line before mine 😅

Any suggestions on how to fix the file and pass the test? Looking at it, it's like Greek to me

**Comment by EzioTheDeadPoet** [comment]
If you go to `files changed` in this pull request and then click edit then you can add the missing `,`
also you need to remove the `,` at the end of the line cause the last line can't have a `,`.

As for the issue in your modlists.json we can check that when the test doesn't stumble over the repositories.json changes.

**Comment by VirtualPandaVR** [comment]
Got it. The instructions saying to add a comma "after the last line" is kind of ambiguous and confusing. Might be worth updating for clarity.

**Comment by EzioTheDeadPoet** [comment]
well it means the original last line 😂

**Comment by EzioTheDeadPoet** [comment]
> MachineUrl/ModlistRepository must not contain any whitespace, use underscores instead: "Panda's Immersive SkyrimVR Experience" ("Panda's Immersive SkyrimVR Experience")

your machine URL can't have spaces or special characters!

**Comment by EzioTheDeadPoet** [comment]
The same actually also applies to your repository name!

**Comment by VirtualPandaVR** [comment]
Got it. Updated to PISE

**Pull request merged**
