### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by JmyX420**
Pull Request for ui listing.

### CODE REVIEW

**Comment by tr4wzified** [comment]
The link to your image is broken. I think you'll want to change it to https://raw.githubusercontent.com/JmyX420/nvmp-radd-modlist/refs/heads/main/NVMPModlistSplash.jpg

**Comment by tr4wzified** [comment]
Oh, and please resize your image first to a smaller resolution, like 1920x1080. It adds unnecessary strain to the gallery otherwise

**Comment by JmyX420** [comment]
> Oh, and please resize your image first to a smaller resolution, like 1920x1080. It adds unnecessary strain to the gallery otherwise

Thanks for the heads up! I've resized it and changed it to .webp format and updated the link in my modlists.json.

**Comment by tr4wzified** [comment]
Perfect! Merged.

**Pull request merged**
