### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by OddlyMistaken**

### CODE REVIEW

**Comment by Lartza** [comment]
You should use `"Dying_Breath":` in the repositories.json, avoid using spaces in most non-human readable cases

As for your modlists.json it also contains errors. When replacing example values you need to remove the <> characters.

You should remove the `"<any tags you want in the UI, each in its own string"` tag

Consider `"image_contains_title"` based on what image you use

Image should be 16:9 aspect ratio (https://www.wabbajack.org/gallery) and an .ico file may or may not work. You should also remove refs/heads from raw urls since WJ might be failing for those currently. (And just use Dying-Breath/main/FILENAME)

machineURL needs to be filled. It's often just simply `dying_breath`

**Comment by OddlyMistaken** [comment]
I took your advice and made these changes. Thank you for the heads up.

**Comment by tr4wzified** [comment]
The < and > is just a template thing. Remove those from the URLs and out of your maintainer name

**Comment by OddlyMistaken** [comment]
Thanks, I removed these. Also I referenced some other .jsons in the repository list and noticed some differences. namely they weren't using $type and had some additional lines such as "official" are those changes I should make as well?

**Pull request merged**
