### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by hitmantb**
Adding:

Fallout 4 VR Modern Tactical Overhaul

"FO4VRMTO": "https://raw.githubusercontent.com/hitmantb/fo4vrmto/main/modlists.json",

Skyrim VR Minimalistic Overhaul - NSFW

"SKVRMONSFW": "https://raw.githubusercontent.com/hitmantb/skvrmonsfw/main/modlists.json"

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
For some reason this pull request is skipping the mandatory GitHub Action validation. So I won't merge it.

Especially since the only reason I can think of for this happening would be if the fork this pull request comes from isn't updated enough to actually include the tests yet(it might be something different but this is the only reason I have encountered in the past for pull requests not triggering the GitHub Actions they should trigger.).

**Comment by EzioTheDeadPoet** [comment]
Ok just checked your repository and for some reason the tests are actually there, but still aren't triggering here 🤔

**Comment by hitmantb** [comment]
Any chance you can copy and paste the two lines and add manually?  Sorry not sure why it is not working.

If not I can try delete my fork and re-add.

**Comment by EzioTheDeadPoet** [comment]
yeah will look into it this evening, in case I forget just ping me in discord. Should be the same username as here now with the new system. (one of the few actually nice things coming from that change, for the people able to get the name they have on other platforms.)

**Comment by hitmantb** [comment]
Created a new pull request after deleting my fork and redownloading:
https://github.com/wabbajack-tools/mod-lists/pull/3346

**Pull request closed without merging**
