### PR TITLE
Added TheMethod to repositories.json

### PR DESCRIPTION
**Pull request by AllstaRawR**
Added a new modlist called TheMethod. I remembered the comma this time.

### CODE REVIEW

**Comment by laritikkanen** [comment]
You should have one modlists.json for all your modlists

**Comment by Lartza** [comment]
You should use one modlists.json for all your modlists and then further PRs (like this one) are unnecessary

**Comment by AllstaRawR** [comment]
> You should use one modlists.json for all your modlists and then further PRs (like this one) are unnecessary
> You should have one modlists.json for all your modlists

Oh! So my FILFY repo would have an additional section in modlists.json that has TheMethod. I think I follow. I will try that.

**Comment by Lartza** [comment]
Yes that would work

**Comment by AllstaRawR** [comment]
Thank you so much for the help! I made this commit and it seemed to work. :)

**Pull request closed without merging**
