### PR TITLE
Update repositories.json for TPF - Zediious Sprinkles

### PR DESCRIPTION
**Pull request by zediious**
Modpack repository/wiki located here https://github.com/zediious/tpfz-sprinkles

Thank you for your time :)

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
https://github.com/zediious/modlists/pull/1
needs to be merged

**Comment by zediious** [comment]
> [zediious/modlists#1](https://github.com/zediious/modlists/pull/1) needs to be merged

Got that merged in, thank you!

**Comment by EzioTheDeadPoet** [comment]
The only thing left before I merge now would be if you checked with @foreverphoenix if they are ok with you naming your list similar to theirs.

**Comment by zediious** [comment]
> The only thing left before I merge now would be if you checked with @foreverphoenix if they are ok with you naming your list similar to theirs.

Indeed I have, here's a screen grab from my direct message asking. I'm not sure if you wanted to wait for Phoenix to confirm themselves.
Screenshot_20230420_161302_Discord

**Pull request merged**
