### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by CharderotheLupe**
Hope this machine url is correct.

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
your maintainers section is wrong.
You need to put `github/CharderotheLupe` in there.
Just comment here when you fixed that.

**Comment by CharderotheLupe** [comment]
Ok, I changed it. Hope that's all it is.

**Comment by tr4wzified** [comment]
I'm merging it, but just letting you know; if you're ever not sure about something, please ask first instead of messing about with the modlists.json since it can cause Wabbajacks gallery to go down.

**Comment by CharderotheLupe** [comment]
Thank you!

**Pull request merged**
