### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by Hotiraripha**
Forgot a comma

### CODE REVIEW

**Comment by Althro** [comment]
Please update your machine ID and remove the `<` from around the links in your modlists json.

**Comment by Hotiraripha** [comment]
Sorry, what is the machine ID meant to be, could you provide an example?

**Comment by Althro** [comment]
Something akin to `Hotisworld` would be fine. The quotation marks are causing the issue

**Comment by Hotiraripha** [comment]
alright, will change now thanks

**Pull request closed without merging**
