### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by Millionsfrost**
Yes

### CODE REVIEW

**Comment by SovnSkyrim** [comment]
your tags look fucked

"
      "<'Vokriinator Black', 'MCO', 'Stances', 'Power Fantasy', 'New Lands', 'New Quests', 'Sexlab+', 'Pandora Engine' "
"

**Comment by Millionsfrost** [comment]
Can you tell me with wrong with the tags? I dont see it.

**Comment by SovnSkyrim** [comment]
from
`    "tags": [
      "testing",
      "<'Vokriinator Black', 'MCO', 'Stances', 'Power Fantasy', 'New Lands', 'New Quests', 'Sexlab+', 'Pandora Engine' "
    ],`

to 
`    "tags": [
      "testing",
      "Vokriinator Black", 
"MCO", 
"Stances",
 "Power Fantasy",
"New Lands",
"New Quests",
"Sexlab+",
 "Pandora Engine"
    ],`

indent as you need, breaks down the list separated by single quotes into pieces separated by double quotes like jsons should; also remove the open ended < that didnt get closed.

**Comment by Millionsfrost** [comment]
I edited it, is it better now?

**Comment by Millionsfrost** [comment]
Sry just finished editing.

**Comment by SovnSkyrim** [comment]
Your json's so bad i'll just do it myself. 
Watch your pull requests

**Comment by Millionsfrost** [comment]
Iam sorry i think i did edit it correct but in the wrong place. Iam just not that familiar with all of these github buttons and stuff :x

**Pull request merged**
