### PR TITLE
Added Deckborn to the repo

### PR DESCRIPTION
**Pull request by Pentonize**

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
@Pentonize the machineURL inside your json file is only the ID of your list.

**Comment by Pentonize** [comment]
> @Pentonize the machineURL inside your json file is only the ID of your list.

So would I need to just have my MachineURL in the modlist.json as "Deckborn" and match that in the .wabbajak file?

**Comment by EzioTheDeadPoet** [comment]
the WJ file is independent from that

also the repository name can be anything (that doesn't contain special characters or whitespaces).

So your repository in the json that you edit here could be named `Pentonize`.

And your machineURL could be `Deckborn` or `Deckborn`.

Then when you want to use the publish update feature in WJ you would put `Pentonize/Deckborn`

Or in a fixed current setup where your wj-repo is called `Deckborn` it would be `Deckborn/deckborn`.

**Comment by EzioTheDeadPoet** [comment]
https://wiki.wabbajack.org/wabbajack_cdn_and_gallery_access/Getting%20CDN%20Access.html

https://wiki.wabbajack.org/wabbajack_cdn_and_gallery_access/Adding%20a%20Custom%20Repository%20to%20Wabbajack.html

**Comment by Pentonize** [comment]
@EzioTheDeadPoet alright I will do that now! Will need to recompile my wabbajak file. Will update the pull request when done!

**Comment by Pentonize** [comment]
@EzioTheDeadPoet I pushed my update to my repo and reuploaded the wabbajack file, is that ok now?

**Pull request merged**
