### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by TwistedModding**

### CODE REVIEW

**Comment by Lartza** [comment]
Modlists.json is invalid JSON and needs readme, website, image and download urls fixed before merging

**Review by tr4wzified — CHANGES_REQUESTED** [review]
See comments from Lartza (also in Discord)

**Comment by TwistedModding** [comment]
Everything should be fixed now @tr4wzified

**Comment by tr4wzified** [comment]
machineURL should not be prefixed with repository name in yhe modlists.json, only in Wabbajack itself

**Comment by TwistedModding** [comment]
Done

**Pull request merged**
