### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by Camora0**

### CODE REVIEW

**Comment by SovnSkyrim** [comment]
Pretty sure it fails due to the readme not existing. A blank github link is better than this (given it does not "display" per se the character string but rather uses it as a link and redirects it).

**Comment by Camora0** [comment]
I have updated my json so it will work properly.

**Comment by Camora0** [comment]
I have directed a URL to the github readme, that might do it

**Comment by SovnSkyrim** [comment]
This looks much better.

**Pull request merged**
