### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by KCisSICKnasty**

### CODE REVIEW

**Comment by tr4wzified** [comment]
Link should be a file called modlists.json, like this: https://raw.githubusercontent.com/KCisSICKnasty/sicknasty/main/modlists.json

Aside from that:
- Please append your repository to the bottom of the file
- Please make sure to keep the JSON valid, you're missing a comma at the end causing this file to break. You can use online tools for this.
- Remove the leading < and also the > at the end of the various strings in your modlists.json, such as the links, tags and author name
- Host your image on GitHub instead of a random site. Please also make sure it's a 1920x1080 image in webp format.
- Remove the game name from your modlists title
- Your modlist download link is not actually pointing to your modlist, but to Halgari's Helper, a testing modlist for developers.

To update this, you don't have to open a new pull request. Simply go to your patch-2 branch and fix up this repositories.json file, and make sure to update your own repository file to solve the issues above. If you're not sure about the format, check any other repository mentioned in this file and the Wabbajack Wiki. If you have questions, ask them in this PR or in #modlist-development-help in the Wabbajack discord server :)

**Comment by KCisSICKnasty** [comment]
"Please append your repository to the bottom of the file" what does this mean?

**Comment by KCisSICKnasty** [comment]
How do I host an image on github?

**Comment by KCisSICKnasty** [comment]
How do I point the modlist to mine?

**Comment by KCisSICKnasty** [comment]
I don't mean to ask so much here when you've given me 2 options, but I've asked for help in wabbajack discord and read the wiki over and over. i just want an answer. :( i do not understand github and didn't know it would be required until i tried to go for featured modlist.

**Comment by tr4wzified** [comment]
Sorry, instead of the comma, the quotation marks around your URL are missing, I didn't see that. You can upload any file if you just open your repository in GitHubs web UI and press add file, left of the green Code button to download the files in the repo.

**Comment by KCisSICKnasty** [comment]
Which URL? I'm not seeing any missing quotation marks.

**Comment by KCisSICKnasty** [comment]
I have the image hosted, but I'm not seeing a way to make it a link or webp.

**Comment by KCisSICKnasty** [comment]
How do I go to my patch-2 branch and edit this? I'm not seeing the ability to edit.

**Comment by KCisSICKnasty** [comment]
???

**Comment by tr4wzified** [comment]
The URL you added to this modlists.json file in this repository does not have quotation marks around it. You have to manually convert your image file to webp format, there's plenty of online converters. If you're not sure what branches are, I recommend looking up some Git(Hub) tutorials and maybe also have a read about what JSON is. I'm sorry but I don't have time to explain everything, there's tons of info online though.

**Comment by KCisSICKnasty** [comment]
I'm not asking you to explain everything about Git. These are things I need to do in order to apply for featured. I'm confused where I am missing quotation marks, because looking at my JSON, everything link related has them. I know what a branch is, but I do not know how to get to what you are telling me to just edit. It makes me want to just submit a new pull request because I cannot find what I need to edit like you are asking me to do and I at least know how to submit a pull request. How do I get to the branch that you are telling me to edit instead of creating a new pull request?

**Comment by tr4wzified** [comment]
If you click the blue button with 'KCisSICKnasty:patch-2' at the top of this PR, that gets you there

**Comment by KCisSICKnasty** [comment]
Okay, I figured it out. I hope I wasn't coming off in anyway angry. GitHub is just not very user friendly to me. I had clicked that blue button before, and it didn't bring me anywhere I understood. What I had to do was, right above your first message, click the "files changed" tab, and then it took me to where I can edit. I did not know that we were currently speaking INSIDE where I needed to be. When you were saying quotes, I thought you were referring to my actual JSON, not my pull request link, so that's my bad. It's been edited, quotation marked, webp'd, de-<>-ified, and all of the things you said. (:

**Comment by tr4wzified** [comment]
Merged, your modlist should appear on the Wabbajack gallery shortly. Image does not have the right dimensions so it'll crop out some bits, but you can change that later if you want.

**Comment by KCisSICKnasty** [comment]
Thank you so much for your patience with me.

**Comment by KCisSICKnasty** [comment]
If I wanted to update this with the new resized image, how would i do that? :O

**Comment by tr4wzified** [comment]
You go to [your repository](https://github.com/KCisSICKnasty/SICKnasty-FO4) and replace Word.webp with a different image. You can do so by clicking Add file > Upload file left of the green download code button

**Comment by KCisSICKnasty** [comment]
Wabbajack wont let me use this to update. :( 

[ERROR] (Wabbajack.CompilerVM) Preflight Check failed, list https://raw.githubusercontent.com/KCisSICKnasty/sicknasty/refs/heads/main/modlists.json not found in any repository

**Pull request merged**
